ranking_strategy: "revenue_optimized"

scoring_formula: "0.6 * engagement + 0.4 * revenue - 0.1 * risk_score"

filters:
  - condition: "offer.isFraudSuppressed == false"
    description: "Exclude fraud-suppressed offers"
  - condition: "user.tier >= 2"
    description: "Only premium users"
  - condition: "offer.category != 'gambling'"
    description: "Exclude gambling offers"

experiment_groups:
  high_value_users:
    scoring_formula: "0.8 * revenue + 0.2 * engagement"
    filters:
      - condition: "user.ltv > 1000"
        description: "High lifetime value users only"
  
  mobile_users:
    scoring_formula: "0.5 * engagement + 0.3 * revenue + 0.2 * mobile_score"
    filters:
      - condition: "device.type == 'mobile'"
        description: "Mobile devices only"
  
  test_group_a:
    ranking_strategy: "engagement_first"
    scoring_formula: "0.9 * engagement + 0.1 * revenue"

# Global configuration
max_results: 50
boost_factors:
  new_offers: 1.2
  trending_offers: 1.1
  personalized_offers: 1.3

# Fallback configuration
fallback:
  ranking_strategy: "simple_score"
  scoring_formula: "base_score"
  max_results: 20